from __future__ import annotations


LAYOUTS = {
    "level-design-curriculum-overview": {
        "text": "right_panel",
        "reason": "底图是流程总览，主体横向信息多；文字放右栏，避免压住流程节点和图标组。",
    },
    "core-gameplay-loop-diagram": {
        "text": "right_panel",
        "reason": "底图中心房间和循环箭头都需要保持完整；文字全部外置，避免遮挡核心循环。",
    },
    "obstacle-action-relation": {
        "text": "right_panel_compact",
        "reason": "底图为六宫格样本板，任何浮动标签都会压住案例；右侧紧凑编号说明最稳。",
    },
    "pacing-emotion-curve": {
        "text": "right_panel",
        "reason": "曲线和底部节奏标尺必须连续可读；文字不放在曲线峰谷上。",
    },
    "precise-metrics-dual-scale-overview": {
        "text": "right_panel",
        "reason": "左右双标尺需要保留对照关系；右侧说明栏承载定义。",
    },
    "precise-character-ability-metrics-grid": {
        "text": "right_panel",
        "reason": "跳弧、半径和网格是重点，说明不覆盖任何落点或角色框。",
    },
    "precise-level-element-difficulty-metrics-matrix": {
        "text": "right_panel_compact",
        "reason": "底图含表格和多个房间样本；说明外置，避免压住矩阵格。",
    },
    "precise-challenge-matrix-four-variations": {
        "text": "right_panel",
        "reason": "四格平台对比要完整保留；文字放右栏对应四个变体。",
    },
    "precise-horizontal-jump-metrics-comparison": {
        "text": "right_panel",
        "reason": "左右跳跃对照的安全区/风险区不能被标签遮挡。",
    },
    "gameplay-matrix-axes": {
        "text": "right_panel",
        "reason": "矩阵本体需要足够大，文字只做外部轴线说明。",
    },
    "platform-world-1-2-progression": {
        "text": "right_panel_compact",
        "reason": "横向关卡进程很长，标签不放在平台路径上。",
    },
    "platform-world-1-2-blockout": {
        "text": "right_panel_compact",
        "reason": "灰盒路径、支路和验证段都在图面内，说明外置。",
    },
    "portal-fling-tutorial-arc": {
        "text": "right_panel_compact",
        "reason": "五个解谜房间面板需要连续阅读，文字不插入面板之间。",
    },
    "portal-fling-room-blockout": {
        "text": "right_panel",
        "reason": "单房间的视线、Portal 面和轨迹弧线是重点，说明外置。",
    },
    "doom-arena-encounter-layout": {
        "text": "right_panel",
        "reason": "竞技场火力锥、环线和资源点不能被文字覆盖。",
    },
    "coop-role-responsibility-matrix": {
        "text": "right_panel",
        "reason": "合作路线、责任区和同步机关需要完整显示。",
    },
    "level-design-iteration-loop": {
        "text": "right_panel_compact",
        "reason": "底图包含多张工件缩略图，说明卡不压缩到图面内。",
    },
    "blockout-level-layout": {
        "text": "right_panel",
        "reason": "总 blockout 信息量最高，文字只能外置，保留主路线、支路和热区。",
    },
    "telemetry-heatmap-matrix-writeback": {
        "text": "right_panel",
        "reason": "热图与矩阵回写关系必须保持清楚，文字不覆盖热区。",
    },
    "genre-matrix-adaptation": {
        "text": "right_panel_compact",
        "reason": "六类型卡片已经很密，说明作为外部图例。",
    },
    "level-design-pitfalls-correction-board": {
        "text": "right_panel_compact",
        "reason": "诊断板含多个 before/after 案例，文字不放进案例格。",
    },
    "five-beat-blockout-exercise": {
        "text": "right_panel_compact",
        "reason": "练习工作表需要保留空白填写区，说明不能占用工作区。",
    },
}


EN_TEXT = {
    "level-design-curriculum-overview": {
        "title": "Curriculum Structure",
        "subtitle": "Goal -> Metrics -> Gameplay Matrix -> Blockout -> Playtest writeback",
        "labels": [
            ("Gameplay Goal", "Define what the player should learn before drawing rooms."),
            ("Metrics", "Convert body size, jump range, speed, sight, and ability radius into shared units."),
            ("Gameplay Matrix", "Describe each beat's action, obstacle, reward, feedback, and emotion."),
            ("Blockout", "Place matrix beats into entrances, routes, nodes, and risks."),
            ("Playtest Writeback", "Use observation, data, and interviews to revise matrix and space."),
        ],
    },
    "core-gameplay-loop-diagram": {
        "title": "Core Gameplay Loop",
        "subtitle": "Observe -> Act -> Resist -> Feedback -> Reward -> Adjust",
        "labels": [
            ("Observe", "Entrances, exits, locks, enemies, and rewards must give readable clues."),
            ("Act", "Move, jump, aim, interact, or cooperate as the matrix's core verbs."),
            ("Resistance", "Enemies, devices, terrain, and resource pressure reshape action."),
            ("Feedback", "Hits, damage, doors, audio, and animation explain success or failure."),
            ("Reward", "Keys, shortcuts, resources, or new paths start the next loop."),
            ("Adjust", "Players revise route, pacing, or skill combination from feedback."),
        ],
    },
    "obstacle-action-relation": {
        "title": "How Obstacles Change Action",
        "subtitle": "Different resistance types rewrite the same core verb",
        "labels": [
            ("Low Wall", "Turns movement into jump timing."),
            ("Moving Platform", "Turns jumping into rhythm reading."),
            ("Narrow Gate", "Turns progress into angle and speed control."),
            ("Vision Enemy", "Turns action into observation and waiting."),
            ("Lock and Key", "Turns the goal into route planning."),
            ("Reward Branch", "Turns safe progress into risk choice."),
        ],
    },
    "pacing-emotion-curve": {
        "title": "Pacing and Emotion Curve",
        "subtitle": "Teaching, practice, validation, and release should form visible pressure changes",
        "labels": [
            ("Low-pressure Teaching", "Introduce the rule with low risk and a clear goal."),
            ("Practice", "Repeat the same skill while changing distance, timing, or sight."),
            ("Pressure Peak", "Combine obstacles to test real understanding."),
            ("Release", "Give rewards, resources, or safety so players can process the lesson."),
            ("Writeback Evidence", "Deaths, stops, detours, and confusion reveal pacing issues."),
        ],
    },
    "precise-metrics-dual-scale-overview": {
        "title": "Metrics Dual Scale",
        "subtitle": "Character ability metrics and level element metrics must share units",
        "labels": [
            ("Character Scale", "Body width, jump range, speed, and ability radius define capability."),
            ("Space Scale", "Door width, corridors, room volume, and route count define permission."),
            ("Risk Radius", "Enemy sight, aggro, and reward distance create difficulty."),
            ("Shared Units", "Matrix, blockout, and test notes should use the same grid."),
        ],
    },
    "precise-character-ability-metrics-grid": {
        "title": "Character Ability Metrics Grid",
        "subtitle": "Draw body, jump, speed, and ability radius as checkable units",
        "labels": [
            ("Body Cell", "Collision size defines minimum passage, step, and cover scale."),
            ("Stable Jump", "Use forgiving landings before asking for limits."),
            ("Risk Jump", "Validation jumps need warning and immediate feedback."),
            ("Ability Radius", "Attack, interact, or scan range must map back to room distance."),
            ("Speed and Reaction", "Movement speed defines chase pressure and timing windows."),
        ],
    },
    "precise-level-element-difficulty-metrics-matrix": {
        "title": "Level Element Difficulty Metrics",
        "subtitle": "Every difficulty change should point to a spatial variable",
        "labels": [
            ("Door and Corridor", "Width affects alignment, escape, and co-op congestion."),
            ("Route Count", "Single routes test; multiple routes create choice and risk layers."),
            ("Enemy Radius", "Sight and aggro areas turn space into pressure."),
            ("Reward Distance", "Rewards near risk create meaningful tradeoffs."),
            ("Raise Difficulty", "Change only a few variables so causes remain diagnosable."),
        ],
    },
    "precise-challenge-matrix-four-variations": {
        "title": "Four Challenge Matrix Variations",
        "subtitle": "One skill varies by direction, distance, combination, and failure cost",
        "labels": [
            ("Vertical Easy", "Low height and wide landing for first teaching."),
            ("Vertical Hard", "Higher or narrower, without adding a new rule."),
            ("Simple Combo", "Combine horizontal and vertical movement for transfer practice."),
            ("Hard Combo", "Distance, timing, and landing approach limits for validation."),
        ],
    },
    "precise-horizontal-jump-metrics-comparison": {
        "title": "Horizontal Jump Comparison",
        "subtitle": "Gap width, landing width, and failure cost create difficulty",
        "labels": [
            ("Easy Gap", "Short gap and wide landing confirm basic input."),
            ("Hard Gap", "Long gap and narrow landing increase failure pressure."),
            ("Stable Zone", "Stable landing should cover beginner error."),
            ("Risk Zone", "Risk landings need clear warning and feedback."),
        ],
    },
    "gameplay-matrix-axes": {
        "title": "Gameplay Matrix Axes",
        "subtitle": "Place action, resistance, reward, feedback, and emotion in one table",
        "labels": [
            ("Action Axis", "The verbs players repeatedly perform."),
            ("Obstacle Axis", "Terrain, enemies, and resource pressure that change action."),
            ("Reward Axis", "Signals where risk is worth taking."),
            ("Feedback Axis", "Explains rules, failure, and success."),
            ("Emotion Axis", "Teaching, practice, validation, and release shape experience."),
        ],
    },
    "platform-world-1-2-progression": {
        "title": "Platform Level Progression",
        "subtitle": "Five beats: introduce, practice, vary, validate, release",
        "labels": [
            ("B01 Introduce", "Low risk shows the route and goal."),
            ("B02 Practice", "Short gaps and wide landings repeat stable jumps."),
            ("B03 Vary", "Add rhythm or moving platforms while keeping the rule."),
            ("B04 Validate", "Combine gap, enemy, or height to test mastery."),
            ("B05 Release", "Lower pressure and reward the finish."),
        ],
    },
    "platform-world-1-2-blockout": {
        "title": "Platform Blockout Sketch",
        "subtitle": "Turn five matrix beats into platforms, gaps, steps, and reward lines",
        "labels": [
            ("Entrance", "Show goal and path direction first."),
            ("Short Jump", "Validate basic input in a low-risk space."),
            ("Repeated Gaps", "Keep gap widths consistent to train rhythm."),
            ("Combo Check", "Combine height, enemy, or reward branch."),
            ("Exit Release", "Reduce pressure and let pacing settle."),
        ],
    },
    "portal-fling-tutorial-arc": {
        "title": "Puzzle Tutorial Arc",
        "subtitle": "Observe -> Operate -> Feedback -> Reuse, avoiding tests before teaching",
        "labels": [
            ("Observe", "Show goal, gap, and interactable surfaces."),
            ("Operate", "Let players place, move, or trigger devices."),
            ("Feedback", "Trajectory, doors, audio, and light confirm the rule."),
            ("Reuse", "Change space while keeping the same rule."),
            ("Validate", "Add timing, route, or resource limits."),
        ],
    },
    "portal-fling-room-blockout": {
        "title": "Puzzle Room Blockout",
        "subtitle": "Entrance sight, portal surfaces, trajectory, target platform, feedback line",
        "labels": [
            ("Entrance Sight", "Players should see target and obstacle relation immediately."),
            ("Portal Surface", "Interactable surfaces must clearly cause the path."),
            ("Trajectory", "The arc should be predictable and explain failure."),
            ("Target Platform", "Landing size defines tolerance."),
            ("Feedback Line", "Door, light, sound, and route confirm the solution."),
        ],
    },
    "doom-arena-encounter-layout": {
        "title": "Shooter Arena Encounter Layout",
        "subtitle": "Loop routes, cover, resources, and enemy angles create combat rhythm",
        "labels": [
            ("Loop Route", "Keeps players moving instead of camping one cover."),
            ("Crossfire", "Enemy angles define pressure peaks."),
            ("Resource Pull", "Ammo, health, and armor pull players into risk."),
            ("Safety Window", "Short cover and corners restore decision time."),
            ("Exit Release", "Pressure drops after clear, enabling review."),
        ],
    },
    "coop-role-responsibility-matrix": {
        "title": "Co-op Role Responsibility Matrix",
        "subtitle": "Separate scouting, pressure, damage, support, rescue, and payoff",
        "labels": [
            ("Scout", "Finds routes, devices, and enemy windows."),
            ("Tank", "Attracts risk or controls enemy sight."),
            ("Damage", "Finishes kills, breaks objects, or pushes."),
            ("Support", "Supplies, rescues, opens doors, or protects retreat."),
            ("Shared Payoff", "Rewards and exits should show everyone's contribution."),
        ],
    },
    "level-design-iteration-loop": {
        "title": "Level Design Iteration Loop",
        "subtitle": "Hypothesis, blockout, test, observe, write back, revise",
        "labels": [
            ("Hypothesis", "Write what the player should learn."),
            ("Blockout", "Verify spatial relations with low art cost."),
            ("Playable Test", "Real input exposes problems."),
            ("Observe Data", "Record deaths, stops, detours, and confusion."),
            ("Matrix Writeback", "Fix causes, not surface symptoms."),
            ("Next Revision", "Every iteration keeps evidence."),
        ],
    },
    "blockout-level-layout": {
        "title": "Blockout Level Layout",
        "subtitle": "Five-beat spatial assembly: entrance, obstacle, reward, validation, exit",
        "labels": [
            ("Beat Mapping", "Every matrix beat needs a spatial location."),
            ("Main Route", "Carries the teaching order from entrance to exit."),
            ("Reward Branch", "Creates choice through risk and distance."),
            ("Validation Room", "Combines learned actions without changing rules suddenly."),
            ("Writeback Point", "Test issues should map to room and matrix cell."),
        ],
    },
    "telemetry-heatmap-matrix-writeback": {
        "title": "Telemetry Heatmap and Matrix Writeback",
        "subtitle": "Use deaths, dwell time, detours, and interviews to revise assumptions",
        "labels": [
            ("Death Hotspot", "Shows where failure happens, not why by itself."),
            ("Dwell Hotspot", "May indicate confusion, observation, or resource choice."),
            ("Detour Trace", "Reveals goal guidance, reward pull, or risk perception issues."),
            ("Interview/Replay", "Explains why players acted that way."),
            ("Matrix Writeback", "Write evidence back to action, obstacle, reward, or feedback."),
        ],
    },
    "genre-matrix-adaptation": {
        "title": "Genre Matrix Adaptation",
        "subtitle": "The same matrix changes verbs and metrics by genre",
        "labels": [
            ("Platformer", "Jump range, landing, rhythm, and failure cost."),
            ("Puzzle", "Observation, hypothesis, operation, feedback."),
            ("Shooter", "Cover, fire angles, resources, and movement pressure."),
            ("Extraction/Stealth", "Route risk, information, resources, and exit windows."),
            ("Co-op", "Roles, sync windows, and rescue responsibility."),
            ("Open World", "Goal guidance, exploration density, and pacing zones."),
        ],
    },
    "level-design-pitfalls-correction-board": {
        "title": "Common Pitfalls and Corrections",
        "subtitle": "Trace symptoms back to matrix, space, metrics, and evidence",
        "labels": [
            ("More Quantity", "More enemies do not equal better difficulty; fix position, sight, resources."),
            ("Unclear Goal", "Entrance sight, exit signal, and reward clues are missing."),
            ("No Metrics", "Gap, door, and radius do not match character ability."),
            ("No-risk Reward", "Reward becomes decoration instead of choice."),
            ("Floating Matrix", "The table is neat but not placed into space."),
            ("Ignored Evidence", "Test data is not written into the next design."),
        ],
    },
    "five-beat-blockout-exercise": {
        "title": "Five-beat Blockout Exercise",
        "subtitle": "Turn a matrix into a walkable, testable, reviewable spatial sketch",
        "labels": [
            ("1 Introduce", "Use one new rule in a safe setup."),
            ("2 Practice", "Repeat the core action with low failure cost."),
            ("3 Variation", "Change spatial condition without changing the rule."),
            ("4 Validate", "Combine learned content and raise pressure."),
            ("5 Release", "Use exit, reward, or safety to close the beat."),
            ("Checklist", "Each beat needs action, obstacle, reward, feedback, and emotion."),
        ],
    },
}


# Boxes are in the native image2 base coordinate space: 1672 x 941.
# They target either blank label fields already present in the generated base
# artwork or low-interference callout areas reserved by the layout.
ANNOTATION_BOXES = {
    "level-design-curriculum-overview": [
        (51, 65, 324, 110),
        (393, 65, 643, 110),
        (709, 65, 968, 110),
        (1030, 65, 1280, 110),
        (1350, 65, 1618, 110),
    ],
    "core-gameplay-loop-diagram": [
        (741, 67, 989, 219),
        (1326, 126, 1456, 284),
        (1350, 382, 1504, 552),
        (1119, 696, 1326, 844),
        (520, 703, 716, 850),
        (292, 363, 466, 552),
    ],
    "obstacle-action-relation": [
        (148, 50, 472, 105),
        (664, 50, 1003, 105),
        (1189, 50, 1551, 105),
        (145, 447, 483, 500),
        (661, 448, 1004, 500),
        (1183, 448, 1546, 500),
    ],
    "pacing-emotion-curve": [
        (236, 59, 410, 101),
        (511, 59, 682, 100),
        (785, 59, 960, 100),
        (1061, 59, 1260, 100),
        (1362, 59, 1540, 100),
    ],
    "precise-metrics-dual-scale-overview": [
        (159, 32, 620, 90),
        (1042, 32, 1501, 90),
        (935, 656, 1619, 773),
        (53, 656, 729, 773),
    ],
    "precise-character-ability-metrics-grid": [
        (648, 28, 1114, 146),
        (29, 25, 477, 97),
        (765, 747, 952, 797),
        (1339, 747, 1517, 797),
        (28, 496, 341, 663),
    ],
    "precise-level-element-difficulty-metrics-matrix": [
        (21, 22, 520, 67),
        (554, 219, 879, 259),
        (1003, 133, 1119, 165),
        (1304, 133, 1466, 165),
        (302, 721, 555, 798),
    ],
    "precise-challenge-matrix-four-variations": [
        (148, 41, 607, 100),
        (956, 41, 1416, 100),
        (148, 468, 607, 523),
        (956, 468, 1416, 524),
    ],
    "precise-horizontal-jump-metrics-comparison": [
        (199, 41, 632, 96),
        (1031, 41, 1466, 96),
        (204, 692, 597, 812),
        (1016, 693, 1214, 812),
    ],
    "gameplay-matrix-axes": [
        (1030, 97, 1639, 170),
        (85, 336, 259, 402),
        (530, 336, 714, 402),
        (808, 336, 992, 402),
        (1046, 681, 1639, 763),
    ],
    "platform-world-1-2-progression": [
        (27, 651, 327, 770),
        (356, 651, 649, 770),
        (679, 651, 981, 770),
        (1009, 651, 1310, 770),
        (1340, 651, 1645, 770),
    ],
    "platform-world-1-2-blockout": [
        (29, 458, 318, 531),
        (360, 458, 645, 531),
        (686, 458, 979, 531),
        (1019, 459, 1307, 531),
        (1350, 460, 1645, 512),
    ],
    "portal-fling-tutorial-arc": [
        (138, 78, 339, 132),
        (477, 78, 666, 132),
        (796, 78, 982, 132),
        (1114, 78, 1301, 132),
        (1431, 78, 1613, 132),
    ],
    "portal-fling-room-blockout": [
        (26, 117, 275, 161),
        (1396, 117, 1645, 160),
        (26, 273, 275, 317),
        (1396, 273, 1645, 317),
        (26, 557, 275, 601),
    ],
    "doom-arena-encounter-layout": [
        (93, 46, 271, 81),
        (1447, 46, 1622, 81),
        (94, 303, 271, 338),
        (1448, 336, 1622, 370),
        (96, 774, 313, 799),
    ],
    "coop-role-responsibility-matrix": [
        (427, 39, 629, 91),
        (770, 39, 1020, 91),
        (1152, 39, 1353, 91),
        (337, 106, 644, 163),
        (1066, 105, 1369, 163),
    ],
    "level-design-iteration-loop": [
        (229, 42, 471, 87),
        (665, 42, 946, 87),
        (1226, 42, 1509, 87),
        (124, 417, 444, 463),
        (1252, 418, 1516, 464),
        (631, 821, 888, 876),
    ],
    "blockout-level-layout": [
        (143, 145, 321, 177),
        (445, 145, 668, 177),
        (775, 145, 985, 177),
        (1073, 145, 1286, 177),
        (1383, 145, 1591, 177),
    ],
    "telemetry-heatmap-matrix-writeback": [
        (282, 46, 696, 82),
        (1009, 85, 1368, 160),
        (1003, 392, 1350, 428),
        (1416, 444, 1615, 477),
        (45, 794, 273, 886),
    ],
    "genre-matrix-adaptation": [
        (32, 37, 257, 72),
        (715, 68, 907, 104),
        (1111, 37, 1345, 71),
        (32, 379, 257, 413),
        (598, 572, 837, 605),
        (1112, 379, 1342, 413),
    ],
    "level-design-pitfalls-correction-board": [
        (122, 44, 442, 82),
        (674, 44, 993, 82),
        (1216, 44, 1547, 83),
        (121, 432, 442, 468),
        (674, 432, 993, 468),
        (1219, 432, 1546, 468),
    ],
    "five-beat-blockout-exercise": [
        (83, 40, 327, 83),
        (435, 41, 660, 83),
        (765, 41, 990, 83),
        (1097, 41, 1314, 83),
        (1415, 41, 1634, 83),
        (1216, 732, 1635, 856),
    ],
}


EXTRA_CALLOUTS = {
    "level-design-curriculum-overview": [
        ((49, 432, 326, 526), ("先定学习目标", "玩家要学会什么，再决定房间和障碍。"), ("Learning Goal", "Define what players learn before rooms and obstacles.")),
        ((391, 435, 643, 526), ("量化能力边界", "把身体、速度、跳距和技能半径变成格。"), ("Ability Metrics", "Convert body, speed, jump, and radius into units.")),
        ((707, 435, 969, 526), ("矩阵化拆解", "每段写清行动、阻力、奖励和反馈。"), ("Matrix Breakdown", "Record action, resistance, reward, and feedback.")),
        ((1028, 435, 1281, 526), ("灰盒落地", "把矩阵节拍排成入口、路线和房间。"), ("Blockout Mapping", "Place beats as entrances, routes, and rooms.")),
        ((1346, 497, 1621, 535), ("测试证据回写", "死亡、停留和绕路要回到矩阵修正。"), ("Evidence Writeback", "Deaths, stops, and detours revise the matrix.")),
    ],
    "pacing-emotion-curve": [
        ((53, 695, 304, 785), ("教学证据", "低压区看玩家是否理解目标。"), ("Teaching Evidence", "Low pressure checks whether the goal is clear.")),
        ((343, 695, 594, 785), ("练习证据", "重复不应只增加失败惩罚。"), ("Practice Evidence", "Repetition should change condition, not just cost.")),
        ((631, 695, 884, 785), ("峰值证据", "组合点要验证已经教过的内容。"), ("Peak Evidence", "Pressure should test taught content.")),
        ((974, 695, 1226, 785), ("释放证据", "奖励和安全区让玩家复盘。"), ("Release Evidence", "Reward and safety let players process.")),
        ((1313, 695, 1566, 785), ("回写证据", "停顿、死亡和绕路决定下一版。"), ("Writeback Evidence", "Stops, deaths, and detours drive revision.")),
    ],
    "precise-metrics-dual-scale-overview": [
        ((772, 445, 902, 545), ("单位映射", "角色能力要换算成空间尺度。"), ("Unit Mapping", "Character ability converts into spatial scale.")),
        ((103, 841, 179, 883), ("身体", ""), ("Body", "")),
        ((273, 841, 348, 883), ("碰撞", ""), ("Collision", "")),
        ((439, 841, 514, 883), ("速度", ""), ("Speed", "")),
        ((592, 841, 666, 883), ("跳距", ""), ("Jump", "")),
        ((750, 841, 824, 883), ("半径", ""), ("Radius", "")),
        ((910, 841, 984, 883), ("门宽", ""), ("Door", "")),
        ((1068, 841, 1142, 883), ("通道", ""), ("Corridor", "")),
        ((1230, 841, 1304, 883), ("房间", ""), ("Room", "")),
        ((1394, 841, 1468, 883), ("视线", ""), ("Sight", "")),
        ((1549, 841, 1618, 883), ("奖励", ""), ("Reward", "")),
    ],
    "precise-level-element-difficulty-metrics-matrix": [
        ((698, 132, 822, 167), ("通道宽", ""), ("Corridor", "")),
        ((850, 132, 982, 167), ("路线形态", ""), ("Route Shape", "")),
        ((1150, 132, 1274, 167), ("奖励距离", ""), ("Reward Dist.", "")),
        ((1488, 132, 1630, 167), ("资源密度", ""), ("Resource Density", "")),
        ((41, 840, 256, 900), ("先看通行", "门宽和走廊决定容错。"), ("Passage First", "Doors and corridors set tolerance.")),
        ((276, 840, 488, 900), ("再看路线", "路线数决定选择压力。"), ("Route Count", "Route count sets choice pressure.")),
        ((510, 840, 722, 900), ("再加敌人", "半径和视线改变风险。"), ("Add Enemies", "Radius and sight change risk.")),
        ((744, 840, 956, 900), ("再放奖励", "距离决定是否值得冒险。"), ("Place Rewards", "Distance decides if risk is worth it.")),
        ((978, 840, 1190, 900), ("最后加资源", "补给位置影响恢复节奏。"), ("Add Resources", "Supply placement shapes recovery.")),
        ((1212, 840, 1632, 900), ("一次只改少数变量", "否则测试无法判断是哪项造成变化。"), ("Change Few Variables", "Otherwise tests cannot isolate the cause.")),
    ],
    "precise-horizontal-jump-metrics-comparison": [
        ((32, 558, 805, 637), ("稳定横跳范例", "短坑、宽落点、低失败代价，适合教学。"), ("Stable Jump Example", "Short gap, wide landing, and low failure cost for teaching.")),
        ((848, 558, 1629, 637), ("高风险横跳范例", "长坑、窄落点、尖刺失败成本，适合验证。"), ("High-risk Jump Example", "Long gap, narrow landing, and spike cost for validation.")),
    ],
    "gameplay-matrix-axes": [
        ((1030, 21, 1639, 92), ("矩阵读法", "每一列是一段 beat，每一行记录动作与反馈。"), ("How to Read", "Each column is one beat; rows record action and feedback.")),
    ],
    "platform-world-1-2-progression": [
        ((31, 50, 319, 104), ("B01 引入", "看见出口，先确认方向。"), ("B01 Introduce", "Show exit and direction first.")),
        ((355, 50, 651, 104), ("B02 练习", "短跳和宽落点建立稳定输入。"), ("B02 Practice", "Short jumps and wide landings build stability.")),
        ((681, 50, 984, 104), ("B03 变奏", "条件变化，但规则保持一致。"), ("B03 Vary", "Change condition while keeping the rule.")),
        ((1014, 50, 1307, 104), ("B04 验证", "组合障碍检查掌握程度。"), ("B04 Validate", "Combine obstacles to check mastery.")),
        ((1345, 50, 1643, 104), ("B05 释放", "降低压力，用奖励收束。"), ("B05 Release", "Lower pressure and close with reward.")),
    ],
    "platform-world-1-2-blockout": [
        ((24, 34, 318, 97), ("B01 入口", "先让玩家看到目标和主路线。"), ("B01 Entrance", "Show goal and main route first.")),
        ((354, 34, 650, 97), ("B02 短跳", "低风险确认基础输入。"), ("B02 Short Jump", "Confirm basic input at low risk.")),
        ((681, 34, 984, 97), ("B03 连续短跳", "保持宽度一致，训练节奏。"), ("B03 Repetition", "Keep spacing consistent for rhythm.")),
        ((1011, 34, 1307, 97), ("B04 组合验证", "高度、敌人或奖励支路一起出现。"), ("B04 Combo Check", "Combine height, enemy, or branch.")),
        ((1342, 34, 1641, 97), ("B05 出口释放", "降低压力，让节奏自然落下。"), ("B05 Exit Release", "Drop pressure and let pacing settle.")),
    ],
    "portal-fling-room-blockout": [
        ((1396, 420, 1645, 464), ("按钮/门锁", "触发物要和结果有清楚连线。"), ("Button/Lock", "Trigger and result need a clear link.")),
        ((26, 419, 275, 464), ("中途反馈", "失败轨迹也要能解释原因。"), ("Mid Feedback", "Failure trajectory should explain why.")),
        ((1396, 558, 1645, 603), ("完成信号", "灯光、门和音效确认解法。"), ("Completion Signal", "Light, door, and audio confirm solution.")),
        ((54, 704, 270, 750), ("阻断风险", "激光和敌人说明失败边界。"), ("Blocking Risk", "Lasers and enemies define failure boundaries.")),
        ((1418, 704, 1643, 750), ("提示灯", "灯光确认门锁状态变化。"), ("Indicator Light", "Light confirms lock state changes.")),
    ],
    "doom-arena-encounter-layout": [
        ((178, 105, 271, 127), ("主循环", ""), ("Main Loop", "")),
        ((178, 140, 271, 163), ("侧路线", ""), ("Side Route", "")),
        ((178, 176, 271, 199), ("补给", ""), ("Resources", "")),
        ((178, 211, 271, 234), ("撤离线", ""), ("Exit Line", "")),
        ((177, 363, 271, 392), ("视线扇区", ""), ("Sight Cone", "")),
        ((177, 410, 271, 438), ("火力牵引", ""), ("Fire Pull", "")),
        ((177, 456, 271, 486), ("交战中心", ""), ("Fight Center", "")),
        ((177, 504, 271, 531), ("绕行压力", ""), ("Detour Risk", "")),
        ((93, 604, 272, 637), ("治疗补给", ""), ("Health", "")),
        ((93, 650, 272, 684), ("弹药补给", ""), ("Ammo", "")),
        ((93, 696, 272, 730), ("奖励补给", ""), ("Reward Supply", "")),
        ((1504, 106, 1622, 153), ("火力线", ""), ("Fire Lane", "")),
        ((1504, 169, 1622, 216), ("安全窗", ""), ("Safety", "")),
        ((1503, 231, 1622, 278), ("出口", ""), ("Exit", "")),
        ((1446, 408, 1622, 451), ("门锁节奏", ""), ("Lock Timing", "")),
        ((1446, 489, 1622, 532), ("奖励释放", ""), ("Reward Release", "")),
        ((1483, 559, 1623, 593), ("高掩体", ""), ("Tall Cover", "")),
        ((1484, 607, 1624, 638), ("长掩体", ""), ("Long Cover", "")),
        ((1484, 654, 1623, 685), ("矮掩体", ""), ("Low Cover", "")),
        ((1484, 701, 1623, 732), ("木箱", ""), ("Crate", "")),
        ((421, 774, 632, 799), ("火力压迫", ""), ("Fire Pressure", "")),
        ((739, 774, 947, 799), ("补给转场", ""), ("Supply Shift", "")),
        ((1045, 774, 1278, 799), ("奖励窗口", ""), ("Reward Window", "")),
        ((1377, 774, 1616, 799), ("终点门锁", ""), ("Final Lock", "")),
    ],
    "coop-role-responsibility-matrix": [
        ((1374, 417, 1652, 530), ("敌方响应", "警觉、追击和锁门改变协作节奏。"), ("Enemy Response", "Alert, chase, and locks change co-op rhythm.")),
        ((1222, 568, 1652, 664), ("救援链路", "倒地、救援和掩护要在同一条线上。"), ("Rescue Chain", "Down, rescue, and cover share one route.")),
        ((1222, 708, 1652, 789), ("共享奖励", "出口奖励应显示所有角色贡献。"), ("Shared Payoff", "Exit reward shows every role's contribution.")),
    ],
    "level-design-iteration-loop": [
        ((654, 599, 928, 645), ("矩阵记录", "把观察证据回写到行动、阻力和奖励。"), ("Matrix Record", "Write observations back to action, resistance, and reward.")),
    ],
    "blockout-level-layout": [
        ((173, 51, 341, 71), ("B01", ""), ("B01", "")),
        ((477, 51, 680, 71), ("B02", ""), ("B02", "")),
        ((810, 51, 987, 71), ("B03", ""), ("B03", "")),
        ((1102, 51, 1286, 71), ("B04", ""), ("B04", "")),
        ((1404, 51, 1596, 71), ("B05", ""), ("B05", "")),
        ((79, 224, 186, 246), ("玩家", ""), ("Player", "")),
        ((79, 259, 186, 280), ("主路", ""), ("Main", "")),
        ((79, 291, 186, 312), ("支路", ""), ("Branch", "")),
        ((79, 323, 186, 343), ("敌方路线", ""), ("Enemy Route", "")),
        ((79, 354, 186, 375), ("验证线", ""), ("Validation", "")),
        ((79, 386, 186, 407), ("视线", ""), ("Sight", "")),
        ((79, 417, 186, 439), ("敌人", ""), ("Enemy", "")),
        ((79, 448, 186, 470), ("陷阱", ""), ("Hazard", "")),
        ((79, 480, 186, 501), ("箱体", ""), ("Crate", "")),
        ((79, 510, 186, 531), ("补给", ""), ("Supply", "")),
        ((79, 541, 186, 562), ("资源", ""), ("Resource", "")),
        ((79, 572, 186, 593), ("奖励", ""), ("Reward", "")),
        ((79, 603, 186, 625), ("钥匙", ""), ("Key", "")),
        ((79, 634, 186, 656), ("门锁", ""), ("Lock", "")),
        ((79, 665, 186, 687), ("出口", ""), ("Exit", "")),
        ((1423, 226, 1629, 253), ("敌人组合", ""), ("Enemy Set", "")),
        ((1423, 339, 1630, 387), ("交叉火力", ""), ("Crossfire", "")),
        ((1423, 403, 1630, 454), ("视线压力", ""), ("Sight Pressure", "")),
        ((1423, 469, 1630, 519), ("陷阱/阻挡", ""), ("Hazard/Block", "")),
        ((1422, 557, 1631, 584), ("奖励跳跃", ""), ("Reward Jump", "")),
        ((1502, 678, 1632, 703), ("资源释放", ""), ("Resource", "")),
        ((30, 827, 262, 871), ("节奏曲线", ""), ("Pacing Curve", "")),
    ],
    "telemetry-heatmap-matrix-writeback": [
        ((1051, 45, 1256, 72), ("回写矩阵", ""), ("Writeback Matrix", "")),
        ((1419, 405, 1617, 426), ("访谈/录像", ""), ("Interview/Replay", "")),
        ((1417, 490, 1615, 523), ("问题解释", ""), ("Explain Cause", "")),
        ((1415, 536, 1615, 568), ("修正假设", ""), ("Revise Hypothesis", "")),
        ((1018, 553, 1337, 582), ("关键片段", ""), ("Key Clips", "")),
        ((1045, 613, 1351, 633), ("高热区问题拆解", ""), ("Hotspot Breakdown", "")),
        ((1538, 646, 1624, 748), ("候选修正", ""), ("Candidate Fix", "")),
    ],
    "genre-matrix-adaptation": [
        ((32, 37, 257, 72), ("平台动作", ""), ("Platformer", "")),
        ((1111, 37, 1345, 71), ("射击遭遇", ""), ("Shooter", "")),
        ((715, 68, 907, 104), ("解谜房间", ""), ("Puzzle", "")),
        ((32, 379, 257, 413), ("搜打撤/潜行", ""), ("Extraction/Stealth", "")),
        ((598, 572, 837, 605), ("合作关卡", ""), ("Co-op", "")),
        ((1112, 379, 1342, 413), ("开放世界", ""), ("Open World", "")),
    ],
    "five-beat-blockout-exercise": [
        ((30, 328, 328, 370), ("行动/障碍/奖励", "填写这一段的核心动词和阻力。"), ("Action / Obstacle / Reward", "Fill in verb and resistance.")),
        ((380, 328, 662, 370), ("行动/障碍/奖励", "重复核心动作，改变空间条件。"), ("Action / Obstacle / Reward", "Repeat action, change condition.")),
        ((710, 328, 989, 370), ("行动/障碍/奖励", "加入变奏，不突然换规则。"), ("Action / Obstacle / Reward", "Add variation without new rules.")),
        ((1041, 328, 1316, 370), ("行动/障碍/奖励", "组合已学内容，提高压力。"), ("Action / Obstacle / Reward", "Combine learned content under pressure.")),
        ((1362, 328, 1636, 370), ("行动/障碍/奖励", "用出口、奖励或安全区收束。"), ("Action / Obstacle / Reward", "Close with exit, reward, or safety.")),
        ((88, 660, 276, 688), ("玩家行动", ""), ("Player Action", "")),
        ((88, 694, 276, 722), ("失败/风险", ""), ("Failure / Risk", "")),
        ((88, 728, 276, 756), ("资源补给", ""), ("Resource Supply", "")),
        ((88, 762, 276, 790), ("奖励目标", ""), ("Reward Goal", "")),
        ((88, 796, 276, 824), ("出口", ""), ("Exit", "")),
        ((88, 830, 276, 858), ("门锁", ""), ("Lock", "")),
        ((785, 660, 1174, 858), ("修正记录", "把测试观察写成下一版修改点。"), ("Revision Notes", "Write playtest observations into next-pass changes.")),
        ((1216, 732, 1635, 856), ("检查", "每段都要有动作、障碍、奖励、反馈和情绪目标。"), ("Review", "Each beat needs action, obstacle, reward, feedback, and emotion.")),
    ],
}
